vscode:
  extensions:
    - magicstack.magicpython@1.1.1:Q+4h8/d9eu9kME/nNfIDlg==
    - ms-python.python@2020.10.332292344:5ctthQ25Qni5/aAuOIUTYQ==
    - formulahendry.auto-close-tag@0.5.10:GSIjAJo5b8OeW5FdWSDA8A==